remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: [Amanda Kerr]
logo: https://github.com/amarkerr/amarkerr.github.io/blob/Assets/logo.png?raw=true
description: [Student Developer || Crafting Clear, Inclusive Experiences]
show_downloads: false
